### ISSUE TITLE
Missing context key `entry_id` in live preview

### ISSUE THREAD

**Issue by simonerd** [visuellverstehen/statamic-anchor-navigation#3]
Within the tag we're looking for the entry id within the tag context ([see here](https://github.com/visuellverstehen/statamic-anchor-navigation/blob/0cd9b6f01d93702d992ab006e3b949256dbc6d23/src/Tags/AnchorNavigation.php#L30)):

```php
if (! $this->entry = $this->context->get('entry_id')->augmentable()) {
    return null;
}
```

That seems to work perfectly fine in the frontend – however, when using the live preview, the `entry_id` key can not be found within the context. You _can_ find however a key `id`, which seems to contain the same information. Changing that key should fix this.

Tested in both 3.4 and 4.1, in an existing project and in a fresh install. I don't know if that bug has always been there and we haven't noticed that before, or if any changes caused that problem.

**Comment by juliawarnke** [comment]
Fix is included in the the latest release v0.3.2-beta.
